// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL2gvKhZnwecL-1C_jtrdUUyH_VYeq0yk',
    appId: '1:168072604794:web:e08f325bbc7d6183425fc3',
    messagingSenderId: '168072604794',
    projectId: 'doctorhunt-distribution-b0a1a',
    authDomain: 'doctorhunt-distribution-b0a1a.firebaseapp.com',
    storageBucket: 'doctorhunt-distribution-b0a1a.firebasestorage.app',
    measurementId: 'G-6T41YZEF3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHAARg6XfyT_CcXyosYUNUdEO_VAxPofY',
    appId: '1:168072604794:android:df0d83c5983b6178425fc3',
    messagingSenderId: '168072604794',
    projectId: 'doctorhunt-distribution-b0a1a',
    storageBucket: 'doctorhunt-distribution-b0a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn23-SqSR-Rcif6asADIaTRvWau1FV3O0',
    appId: '1:168072604794:ios:fc6e613980fa9229425fc3',
    messagingSenderId: '168072604794',
    projectId: 'doctorhunt-distribution-b0a1a',
    storageBucket: 'doctorhunt-distribution-b0a1a.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn23-SqSR-Rcif6asADIaTRvWau1FV3O0',
    appId: '1:168072604794:ios:fc6e613980fa9229425fc3',
    messagingSenderId: '168072604794',
    projectId: 'doctorhunt-distribution-b0a1a',
    storageBucket: 'doctorhunt-distribution-b0a1a.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL2gvKhZnwecL-1C_jtrdUUyH_VYeq0yk',
    appId: '1:168072604794:web:3820390bc33c5594425fc3',
    messagingSenderId: '168072604794',
    projectId: 'doctorhunt-distribution-b0a1a',
    authDomain: 'doctorhunt-distribution-b0a1a.firebaseapp.com',
    storageBucket: 'doctorhunt-distribution-b0a1a.firebasestorage.app',
    measurementId: 'G-G7F7442BQ7',
  );
}
