default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:168072604794:android:df0d83c5983b6178425fc3",
      firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type:"APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk ",
      upload_timeout: 600,
      testers: "mariamattef656@gmail.com,ahmed36085361@gmail.com",
      release_notes: "This is a demo release"
  )
  end

 
end
