default_platform(:android)

platform :android do
  desc "Lane for Andtoid Firebase App Distribtion"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:168072604794:android:df0d83c5983b6178425fc3",
    testers: "mariamattef656@gmail.com",
    firebase_cli_token:"1//039mq4CWV6vTvCgYIARAAGAMSNwF-L9IrULxMSkKigj1rQSORAU1ugcVKo-3ToDXjhpHPW45gMxSnPy_12PedP-SOR3pLI1LnSx8",
    android_artifact_type:	"APK",
  android_artifact_path: "./build/app/outputs/flutter-apk/app-production-release.apk",
    release_notes: "This is a demo release"
  )
  end

 
end
